# Generated by Django 5.2.8 on 2025-11-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_payment_url_payment_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
