# Generated by Django 5.2.8 on 2025-11-12 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец урока",
            ),
            preserve_default=False,
        ),
    ]
