# Generated by Django 5.2.8 on 2025-11-15 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_lesson_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Сумма оплаты")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "stripe_product_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="ID продукта Stripe"),
                ),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="ID цены Stripe"),
                ),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"),
                ),
                ("payment_url", models.URLField(blank=True, null=True, verbose_name="Ссылка на оплату Stripe")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
