# Generated by Django 5.2.8 on 2025-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="ID сессии Stripe"),
        ),
    ]
