# Generated by Django 5.2.8 on 2025-11-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_payment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Ссылка на оплату Stripe"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"),
        ),
    ]
